services:
  rproxy:
    image: nginx:alpine
    ports:
      - "8000:80"
    environment:
      NGINX_CONFIG: |
        upstream web {
          server web:5000;
        }

        server {
          listen 80;
    
          location / {
            proxy_pass http://web;
          }
        }
    command:
      /bin/sh -c "echo \"$$NGINX_CONFIG\" > /etc/nginx/conf.d/default.conf; nginx -g \"daemon off;\""
    depends_on:
      - web
  web:
    build: .
    environment:
      # Optional env var below. If set, will be displayed as the greeting. If unset (e.g. GREETING: ), the default greeting is used.
      GREETING: "Congrats on winning the lottery!"
    ports:
      - "5000:5000"